//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quanlynhathuoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYNHATHUOCEntities : DbContext
    {
        public QUANLYNHATHUOCEntities()
            : base("name=QUANLYNHATHUOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblChiTietDT> tblChiTietDTs { get; set; }
        public virtual DbSet<tblChiTietHDNhapthuoc> tblChiTietHDNhapthuocs { get; set; }
        public virtual DbSet<tblDonThuoc> tblDonThuocs { get; set; }
        public virtual DbSet<tblHoaDonNhapThuoc> tblHoaDonNhapThuocs { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblLoaiThuoc> tblLoaiThuocs { get; set; }
        public virtual DbSet<tblNhaCungCap> tblNhaCungCaps { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoans { get; set; }
        public virtual DbSet<tblThuoc> tblThuocs { get; set; }
    }
}
