//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quanlynhathuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietDT
    {
        public int imaHD { get; set; }
        public string smaThuoc { get; set; }
        public Nullable<double> fGiaBan { get; set; }
        public Nullable<double> isoLuong { get; set; }
        public Nullable<double> fChietKhau { get; set; }
    
        public virtual tblDonThuoc tblDonThuoc { get; set; }
        public virtual tblThuoc tblThuoc { get; set; }
    }
}
