//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quanlynhathuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDonThuoc()
        {
            this.tblChiTietDTs = new HashSet<tblChiTietDT>();
        }

        public int imaHD { get; set; } // hoặc thêm thuộc tính smaHD nếu cần thiết
        public string smaNV { get; set; } // thêm vào nếu thiếu
        public string smaKH { get; set; }

        public int sMaHD { get; set; } // thay đổi từ imaHD sang sMaHD nếu mã nguồn sử dụng sMaHD
        public string sDiachiGH { get; set; } // thay đổi từ sDiaChiGH nếu mã nguồn sử dụng sDiachiGH
        public DateTime? dNgayLapHD { get; set; } // thay đổi từ dngayLapHD nếu mã nguồn sử dụng dNgayLapHD
        public DateTime? dNgayGiaoHang { get; set; }

        public string sDiaChiGH { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietDT> tblChiTietDTs { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
