//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quanlynhathuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonNhapThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDonNhapThuoc()
        {
            this.tblChiTietHDNhapthuocs = new HashSet<tblChiTietHDNhapthuoc>();
        }
    
        public string imaHD { get; set; }
        public string smaNV { get; set; }
        public Nullable<System.DateTime> dngayHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDNhapthuoc> tblChiTietHDNhapthuocs { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
