//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Quanlynhathuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.tblDonThuocs = new HashSet<tblDonThuoc>();
            this.tblHoaDonNhapThuocs = new HashSet<tblHoaDonNhapThuoc>();
        }
    
        public string smaNV { get; set; }
        public string stenNV { get; set; }
        public Nullable<System.DateTime> dngaySinh { get; set; }
        public Nullable<bool> bgioiTinh { get; set; }
        public string squeQuan { get; set; }
        public Nullable<System.DateTime> dngayVL { get; set; }
        public Nullable<double> fluongCB { get; set; }
        public Nullable<double> iphuCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonThuoc> tblDonThuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoaDonNhapThuoc> tblHoaDonNhapThuocs { get; set; }
        public virtual tblTaiKhoan tblTaiKhoan { get; set; }
    }
}
